

# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: cp files
      run: mkdir build && cp *.html build

    - name: Tencent Cloud COS Action
      uses: TencentCloud/cos-action@v1
      with:
        # Tencent cloud secret id. Should be referred to a encrypted environment variable
        secret_id: ${{secrets.SECRET_ID}}
        # Tencent cloud secret key. Should be referred to a encrypted environment variable
        secret_key: ${{secrets.SECRET_KEY}}
        # COS bucket name
        cos_bucket: wiki-1251760823
        # COS bucket region
        cos_region: ap-hongkong
        # Local path to be uploaded to COS. Directory or file is allowed
        local_path: build
        # COS path to put the local files in on COS
        remote_path: /
        # Set to true for cleaning files on COS path which are not existed in local path. Default is false
